'''
   (C) 2025 Raryel C. Souza
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

class Google_Speech:
    supported_languages_list = ["en-US - English (United States)",
                                    "cmn-Hans-CN - Chinese (Simplified, China)",
                                    "cmn-Hant-TW - Chinese (Traditional, Taiwan)",
                                    "yue-Hant-HK - Cantonese (Traditional, HK)",
                                    "en-AU - English (Australia)",
                                    "en-CA - English (Canada)",
                                    "en-GB - English (United Kingdom)",
                                    "en-HK - English (Hong Kong)",
                                    "en-IN - English (India)",
                                    "en-GB - English (Ireland)",
                                    "en-NZ - English (New Zealand)",
                                    "en-PH - English (Philippines)",
                                    "en-SG - English (Singapore)",
                                    "af - Afrikaans",
                                    "ar - Arabic",
                                    'ar-DZ - Arabic (Algeria)',
                                    'ar-EG - Arabic (Egypt)',
                                    'ar-IQ - Arabic (Iraq)',
                                    'ar-IS - Arabic (Israel)',
                                    'ar-JO - Arabic (Jordan)',
                                    'ar-KW - Arabic (Kuwait)',
                                    'ar-LB - Arabic (Lebanon)',
                                    'ar-MA - Arabic (Morocco)',
                                    'ar-OM - Arabic (Oman)',
                                    'ar-QA - Arabic (Qatar)',
                                    'ar-SA - Arabic (Saudi Arabia)',
                                    'ar-PS - Arabic (State of Palestine)',
                                    'ar-TN - Arabic (Tunisia)',
                                    'ar-AE - Arabic (United Arab Emirates)',
                                    'ar-YE - Arabic (Yemen)',
                                    "az - Azerbaijani",
                                    "be - Belarusian",
                                    "bg - Bulgarian",
                                    "bn - Bengali",
                                    "bs - Bosnian",
                                    "ca - Catalan",
                                    "ceb -Cebuano",
                                    "cs - Czech",
                                    "cy - Welsh",
                                    "da - Danish",
                                    "de - German",
                                    'de-AT - German (Austria)',
                                    'de-CH - German (Switzerland)',
                                    "el - Greek",
                                    "eo - Esperanto",
                                    'es-ES - Spanish (Spain)',
                                    'es-AR - Spanish (Argentina)',
                                    'es-BO - Spanish (Bolivia)',
                                    'es-CL - Spanish (Chile)',
                                    'es-CO - Spanish (Colombia)',
                                    'es-CR - Spanish (Costa Rica)',
                                    'es-DO - Spanish (Dominican Republic)',
                                    'es-EC - Spanish (Ecuador)',
                                    'es-GT - Spanish (Guatemala)',
                                    'es-HN - Spanish (Honduras)',
                                    'es-MX - Spanish (Mexico)',
                                    'es-NI - Spanish (Nicaragua)',
                                    'es-PA - Spanish (Panama)',
                                    'es-PE - Spanish (Peru)',
                                    'es-PR - Spanish (Puerto Rico)',
                                    'es-PY - Spanish (Paraguay)',
                                    'es-SV - Spanish (El Salvador)',
                                    'es-UY - Spanish (Uruguay)',
                                    'es-US - Spanish (United States)',
                                    'es-VE - Spanish (Venezuela)',
                                    "et - Estonian",
                                    "eu - Basque",
                                    "fa - Persian",
                                    'fil-PH - Filipino (Philippines)',
                                    "fi - Finnish",
                                    "fr - French",
                                    'fr-BE - French (Belgium)',
                                    'fr-CA - French (Canada)',
                                    'fr-CH - French (Switzerland)',
                                    "ga - Irish",
                                    "gl - Galician",
                                    "gu -Gujarati",
                                    "ha - Hausa",
                                    "hi - Hindi",
                                    "hmn - Hmong",
                                    "hr - Croatian",
                                    "ht - Haitian Creole",
                                    "hu - Hungarian",
                                    "hy - Armenian",
                                    "id - Indonesian",
                                    "ig - Igbo",
                                    "is - Icelandic",
                                    "it - Italian",
                                    'it-CH - Italian (Switzerland)',
                                    "iw - Hebrew",
                                    "ja - Japanese",
                                    "jw - Javanese",
                                    "ka - Georgian",
                                    "kk - Kazakh",
                                    "km - Khmer",
                                    "kn - Kannada",
                                    "ko - Korean",
                                    "la - Latin",
                                    "lo - Lao",
                                    "lt - Lithuanian",
                                    "lv - Latvian",
                                    "mg - Malagasy",
                                    "mi - Maori",
                                    "mk - Macedonian",
                                    "ml - Malayalam",
                                    "mn - Mongolian",
                                    "mr - Marathi",
                                    "ms - Malay",
                                    "mt - Maltese",
                                    "my - Myanmar (Burmese)",
                                    "ne - Nepali",
                                    "nl - Dutch",
                                    "no - Norwegian",
                                    "ny - Chichewa",
                                    "pa - Punjabi",
                                    "pl - Polish",
                                    "pt-BR - Portuguese (Brazil)",
                                    "pt-PT - Portuguese (Portugal)",
                                    "ro - Romanian",
                                    "ru - Russian",
                                    "si - Sinhala",
                                    "sk - Slovak",
                                    "sl - Slovenian",
                                    "so - Somali",
                                    "sq - Albanian",
                                    "sr - Serbian",
                                    "st - Sesotho",
                                    "su - Sudanese",
                                    "sv - Swedish",
                                    "sw - Swahili",
                                    "ta - Tamil",
                                    'ta-IN - Tamil (India)',
                                    'ta-MY - Tamil (Malaysia)',
                                    'ta-SG - Tamil (Singapore)',
                                    'ta-LK - Tamil (Sri Lanka)',
                                    "te - Telugu",
                                    "tg - Tajik",
                                    "th - Thai",
                                    "tl - Filipino",
                                    "tr - Turkish",
                                    "uk - Ukrainian",
                                    "ur - Urdu",
                                    "uz - Uzbek",
                                    "vi - Vietnamese",
                                    "yi - Yiddish",
                                    "yo - Yoruba",
                                    "zu - Zulu"]
    @staticmethod
    def get_supported_languages():
        return Google_Speech.supported_languages_list